doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            user_id: 'App\Auth\Infrastructure\Persistence\Doctrine\UserIdType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AuthUser:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Auth/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Auth\Domain'
                alias: App
