exercise_create:
  path: /api/v1/sport/exercises
  controller: App\Apps\External\Pub\Controller\Sport\Exercise\ExerciseCreateController
  defaults: { auth: true }
  methods: [POST]

exercise_get:
  path: /api/v1/sport/exercises/{id}
  controller: App\Apps\External\Pub\Controller\Sport\Exercise\ExerciseGetController
  defaults: { auth: true }
  methods: [GET]

exercises_get:
  path: /api/v1/sport/exercises
  controller: App\Apps\External\Pub\Controller\Sport\Exercise\ExercisesGetController
  defaults: { auth: true }
  methods: [ GET ]

exercise_update:
  path: /api/v1/sport/exercises/{id}
  controller: App\Apps\External\Pub\Controller\Sport\Exercise\ExerciseUpdateController
  defaults: { auth: true }
  methods: [ PUT ]

exercise_delete:
  path: /api/v1/sport/exercises/{id}
  controller: App\Apps\External\Pub\Controller\Sport\Exercise\ExerciseDeleteController
  defaults: { auth: true }
  methods: [DELETE]